### ISSUE TITLE
help

### ISSUE THREAD

**Issue by thebeast102** [natrixdev/tiktok_share-bot#1]
the program instantly closes after i open it how do i fix that

**Comment by thebeast102** [comment]
i ran it in visual studio code and got this error ModuleNotFoundError: No module named 'requests'
i dont know what it means but if you could help that would be awesome

**Comment by superintendent2521** [comment]
you need to run pip install requests and mot likely pip install utils

**Comment by natrixdev** [comment]
> i ran it in visual studio code and got this error ModuleNotFoundError: No module named 'requests' i dont know what it means but if you could help that would be awesome

Hi, thx for using my code, you just need to go in your terminal and type `pip install requests `  and do it for all the required modules
