### ISSUE TITLE
Title Not Found

### ISSUE THREAD

**Issue by Gkumaraw** [natrixdev/tiktok_share-bot#3]
[+] Sending shares on https://www.tiktok.com/@bulan.ii, amount of shares : [319]
sh: 1: title: not found

**Comment by natrixdev** [comment]
Hi [Gkumaraw](https://github.com/Gkumaraw), 

This may be an issue with your OS package. Try to update python on your machine. 

Thanks for your feedback

**Comment by natrixdev** [comment]
But this issue is not critical for the share bot program, it will work
